package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alarms generated by hbm2java
 */
public class Alarms  implements java.io.Serializable {


     private Integer id;
     private Devices devices;
     private String data;
     private Date regtime;
     private String desc;
     private Integer status;
     private String type;

    public Alarms() {
    }

	
    public Alarms(Devices devices) {
        this.devices = devices;
    }
    public Alarms(Devices devices, String data, Date regtime, String desc, Integer status, String type) {
       this.devices = devices;
       this.data = data;
       this.regtime = regtime;
       this.desc = desc;
       this.status = status;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Devices getDevices() {
        return this.devices;
    }
    
    public void setDevices(Devices devices) {
        this.devices = devices;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


