package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String categorycol;
     private Set activitieses = new HashSet(0);

    public Category() {
    }

    public Category(String name, String categorycol, Set activitieses) {
       this.name = name;
       this.categorycol = categorycol;
       this.activitieses = activitieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategorycol() {
        return this.categorycol;
    }
    
    public void setCategorycol(String categorycol) {
        this.categorycol = categorycol;
    }
    public Set getActivitieses() {
        return this.activitieses;
    }
    
    public void setActivitieses(Set activitieses) {
        this.activitieses = activitieses;
    }




}


