package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomersHasTarrif generated by hbm2java
 */
public class CustomersHasTarrif  implements java.io.Serializable {


     private Integer id;
     private Customers customers;
     private Tarrif tarrif;
     private Integer status;
     private Set invoices = new HashSet(0);

    public CustomersHasTarrif() {
    }

	
    public CustomersHasTarrif(Customers customers, Tarrif tarrif) {
        this.customers = customers;
        this.tarrif = tarrif;
    }
    public CustomersHasTarrif(Customers customers, Tarrif tarrif, Integer status, Set invoices) {
       this.customers = customers;
       this.tarrif = tarrif;
       this.status = status;
       this.invoices = invoices;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Tarrif getTarrif() {
        return this.tarrif;
    }
    
    public void setTarrif(Tarrif tarrif) {
        this.tarrif = tarrif;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


