package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer id;
     private Customertype customertype;
     private Domain domain;
     private Organization organization;
     private Integer status;
     private String contactdata;
     private String person;
     private String cardname;
     private String cardtype;
     private String cardno;
     private String cardcvno;
     private Date expiredate;
     private Date regtime;
     private String email;
     private Set customersHasTarrifs = new HashSet(0);
     private Set invoiceregistries = new HashSet(0);
     private Set objtses = new HashSet(0);
     private Set communications = new HashSet(0);

    public Customers() {
    }

	
    public Customers(Customertype customertype, Domain domain, Organization organization) {
        this.customertype = customertype;
        this.domain = domain;
        this.organization = organization;
    }
    public Customers(Customertype customertype, Domain domain, Organization organization, Integer status, String contactdata, String person, String cardname, String cardtype, String cardno, String cardcvno, Date expiredate, Date regtime, String email, Set customersHasTarrifs, Set invoiceregistries, Set objtses, Set communications) {
       this.customertype = customertype;
       this.domain = domain;
       this.organization = organization;
       this.status = status;
       this.contactdata = contactdata;
       this.person = person;
       this.cardname = cardname;
       this.cardtype = cardtype;
       this.cardno = cardno;
       this.cardcvno = cardcvno;
       this.expiredate = expiredate;
       this.regtime = regtime;
       this.email = email;
       this.customersHasTarrifs = customersHasTarrifs;
       this.invoiceregistries = invoiceregistries;
       this.objtses = objtses;
       this.communications = communications;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customertype getCustomertype() {
        return this.customertype;
    }
    
    public void setCustomertype(Customertype customertype) {
        this.customertype = customertype;
    }
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getContactdata() {
        return this.contactdata;
    }
    
    public void setContactdata(String contactdata) {
        this.contactdata = contactdata;
    }
    public String getPerson() {
        return this.person;
    }
    
    public void setPerson(String person) {
        this.person = person;
    }
    public String getCardname() {
        return this.cardname;
    }
    
    public void setCardname(String cardname) {
        this.cardname = cardname;
    }
    public String getCardtype() {
        return this.cardtype;
    }
    
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }
    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    public String getCardcvno() {
        return this.cardcvno;
    }
    
    public void setCardcvno(String cardcvno) {
        this.cardcvno = cardcvno;
    }
    public Date getExpiredate() {
        return this.expiredate;
    }
    
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getCustomersHasTarrifs() {
        return this.customersHasTarrifs;
    }
    
    public void setCustomersHasTarrifs(Set customersHasTarrifs) {
        this.customersHasTarrifs = customersHasTarrifs;
    }
    public Set getInvoiceregistries() {
        return this.invoiceregistries;
    }
    
    public void setInvoiceregistries(Set invoiceregistries) {
        this.invoiceregistries = invoiceregistries;
    }
    public Set getObjtses() {
        return this.objtses;
    }
    
    public void setObjtses(Set objtses) {
        this.objtses = objtses;
    }
    public Set getCommunications() {
        return this.communications;
    }
    
    public void setCommunications(Set communications) {
        this.communications = communications;
    }




}


