package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customertype generated by hbm2java
 */
public class Customertype  implements java.io.Serializable {


     private Integer id;
     private String table1col;
     private Set customerses = new HashSet(0);

    public Customertype() {
    }

    public Customertype(String table1col, Set customerses) {
       this.table1col = table1col;
       this.customerses = customerses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTable1col() {
        return this.table1col;
    }
    
    public void setTable1col(String table1col) {
        this.table1col = table1col;
    }
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }




}


