package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Devices generated by hbm2java
 */
public class Devices  implements java.io.Serializable {


     private String id;
     private Objts objts;
     private String imei;
     private String type;
     private String name;
     private String appid;
     private String model;
     private String timezone;
     private String note;
     private String mobile;
     private String acc;
     private String ngs;
     private String attachto;
     private String attachref;
     private String exlp1;
     private String exlp2;
     private String exlp3;
     private String exlp4;
     private String maker;
     private String cal;
     private String code;
     private Date regtime;
     private Set alarmses = new HashSet(0);
     private Set milages = new HashSet(0);
     private Set tracklogs = new HashSet(0);
     private Set loginlogs = new HashSet(0);

    public Devices() {
    }

	
    public Devices(String id) {
        this.id = id;
    }
    public Devices(String id, Objts objts, String imei, String type, String name, String appid, String model, String timezone, String note, String mobile, String acc, String ngs, String attachto, String attachref, String exlp1, String exlp2, String exlp3, String exlp4, String maker, String cal, String code, Date regtime, Set alarmses, Set milages, Set tracklogs, Set loginlogs) {
       this.id = id;
       this.objts = objts;
       this.imei = imei;
       this.type = type;
       this.name = name;
       this.appid = appid;
       this.model = model;
       this.timezone = timezone;
       this.note = note;
       this.mobile = mobile;
       this.acc = acc;
       this.ngs = ngs;
       this.attachto = attachto;
       this.attachref = attachref;
       this.exlp1 = exlp1;
       this.exlp2 = exlp2;
       this.exlp3 = exlp3;
       this.exlp4 = exlp4;
       this.maker = maker;
       this.cal = cal;
       this.code = code;
       this.regtime = regtime;
       this.alarmses = alarmses;
       this.milages = milages;
       this.tracklogs = tracklogs;
       this.loginlogs = loginlogs;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Objts getObjts() {
        return this.objts;
    }
    
    public void setObjts(Objts objts) {
        this.objts = objts;
    }
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAcc() {
        return this.acc;
    }
    
    public void setAcc(String acc) {
        this.acc = acc;
    }
    public String getNgs() {
        return this.ngs;
    }
    
    public void setNgs(String ngs) {
        this.ngs = ngs;
    }
    public String getAttachto() {
        return this.attachto;
    }
    
    public void setAttachto(String attachto) {
        this.attachto = attachto;
    }
    public String getAttachref() {
        return this.attachref;
    }
    
    public void setAttachref(String attachref) {
        this.attachref = attachref;
    }
    public String getExlp1() {
        return this.exlp1;
    }
    
    public void setExlp1(String exlp1) {
        this.exlp1 = exlp1;
    }
    public String getExlp2() {
        return this.exlp2;
    }
    
    public void setExlp2(String exlp2) {
        this.exlp2 = exlp2;
    }
    public String getExlp3() {
        return this.exlp3;
    }
    
    public void setExlp3(String exlp3) {
        this.exlp3 = exlp3;
    }
    public String getExlp4() {
        return this.exlp4;
    }
    
    public void setExlp4(String exlp4) {
        this.exlp4 = exlp4;
    }
    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }
    public String getCal() {
        return this.cal;
    }
    
    public void setCal(String cal) {
        this.cal = cal;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Set getAlarmses() {
        return this.alarmses;
    }
    
    public void setAlarmses(Set alarmses) {
        this.alarmses = alarmses;
    }
    public Set getMilages() {
        return this.milages;
    }
    
    public void setMilages(Set milages) {
        this.milages = milages;
    }
    public Set getTracklogs() {
        return this.tracklogs;
    }
    
    public void setTracklogs(Set tracklogs) {
        this.tracklogs = tracklogs;
    }
    public Set getLoginlogs() {
        return this.loginlogs;
    }
    
    public void setLoginlogs(Set loginlogs) {
        this.loginlogs = loginlogs;
    }




}


