package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1



/**
 * DomainHasConfiguration generated by hbm2java
 */
public class DomainHasConfiguration  implements java.io.Serializable {


     private Integer id;
     private Configuration configuration;
     private Domain domain;
     private String value;
     private Integer status;

    public DomainHasConfiguration() {
    }

	
    public DomainHasConfiguration(Configuration configuration, Domain domain) {
        this.configuration = configuration;
        this.domain = domain;
    }
    public DomainHasConfiguration(Configuration configuration, Domain domain, String value, Integer status) {
       this.configuration = configuration;
       this.domain = domain;
       this.value = value;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Configuration getConfiguration() {
        return this.configuration;
    }
    
    public void setConfiguration(Configuration configuration) {
        this.configuration = configuration;
    }
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


