package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Domain generated by hbm2java
 */
public class Domain  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String type;
     private String telephone;
     private Double visitcharge;
     private Integer status;
     private Date regtime;
     private Date opentime;
     private Date closetime;
     private String lang;
     private String lat;
     private String moto;
     private String logo;
     private String image;
     private Set domainHasConfigurations = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set customerses = new HashSet(0);

    public Domain() {
    }

    public Domain(String name, String address, String type, String telephone, Double visitcharge, Integer status, Date regtime, Date opentime, Date closetime, String lang, String lat, String moto, String logo, String image, Set domainHasConfigurations, Set logins, Set customerses) {
       this.name = name;
       this.address = address;
       this.type = type;
       this.telephone = telephone;
       this.visitcharge = visitcharge;
       this.status = status;
       this.regtime = regtime;
       this.opentime = opentime;
       this.closetime = closetime;
       this.lang = lang;
       this.lat = lat;
       this.moto = moto;
       this.logo = logo;
       this.image = image;
       this.domainHasConfigurations = domainHasConfigurations;
       this.logins = logins;
       this.customerses = customerses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Double getVisitcharge() {
        return this.visitcharge;
    }
    
    public void setVisitcharge(Double visitcharge) {
        this.visitcharge = visitcharge;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Date getOpentime() {
        return this.opentime;
    }
    
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }
    public Date getClosetime() {
        return this.closetime;
    }
    
    public void setClosetime(Date closetime) {
        this.closetime = closetime;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getMoto() {
        return this.moto;
    }
    
    public void setMoto(String moto) {
        this.moto = moto;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getDomainHasConfigurations() {
        return this.domainHasConfigurations;
    }
    
    public void setDomainHasConfigurations(Set domainHasConfigurations) {
        this.domainHasConfigurations = domainHasConfigurations;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }




}


