package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoiceregistry generated by hbm2java
 */
public class Invoiceregistry  implements java.io.Serializable {


     private Integer id;
     private Customers customers;
     private String no;
     private String total;
     private Set invoices = new HashSet(0);

    public Invoiceregistry() {
    }

	
    public Invoiceregistry(Customers customers) {
        this.customers = customers;
    }
    public Invoiceregistry(Customers customers, String no, String total, Set invoices) {
       this.customers = customers;
       this.no = no;
       this.total = total;
       this.invoices = invoices;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


