package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1



/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private CustomersHasTarrif customersHasTarrif;
     private Invoiceregistry invoiceregistry;
     private Double subtotal;

    public Invoice() {
    }

	
    public Invoice(CustomersHasTarrif customersHasTarrif, Invoiceregistry invoiceregistry) {
        this.customersHasTarrif = customersHasTarrif;
        this.invoiceregistry = invoiceregistry;
    }
    public Invoice(CustomersHasTarrif customersHasTarrif, Invoiceregistry invoiceregistry, Double subtotal) {
       this.customersHasTarrif = customersHasTarrif;
       this.invoiceregistry = invoiceregistry;
       this.subtotal = subtotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CustomersHasTarrif getCustomersHasTarrif() {
        return this.customersHasTarrif;
    }
    
    public void setCustomersHasTarrif(CustomersHasTarrif customersHasTarrif) {
        this.customersHasTarrif = customersHasTarrif;
    }
    public Invoiceregistry getInvoiceregistry() {
        return this.invoiceregistry;
    }
    
    public void setInvoiceregistry(Invoiceregistry invoiceregistry) {
        this.invoiceregistry = invoiceregistry;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }




}


