package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer id;
     private Login login;
     private String description;
     private String ip;
     private Date regtime;
     private String tasktype;
     private String person;

    public Log() {
    }

    public Log(Login login, String description, String ip, Date regtime, String tasktype, String person) {
       this.login = login;
       this.description = description;
       this.ip = ip;
       this.regtime = regtime;
       this.tasktype = tasktype;
       this.person = person;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getTasktype() {
        return this.tasktype;
    }
    
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype;
    }
    public String getPerson() {
        return this.person;
    }
    
    public void setPerson(String person) {
        this.person = person;
    }




}


