package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Loginlog generated by hbm2java
 */
public class Loginlog  implements java.io.Serializable {


     private Integer id;
     private Devices devices;
     private Date regtime;
     private String spare;
     private Integer status;

    public Loginlog() {
    }

	
    public Loginlog(Devices devices) {
        this.devices = devices;
    }
    public Loginlog(Devices devices, Date regtime, String spare, Integer status) {
       this.devices = devices;
       this.regtime = regtime;
       this.spare = spare;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Devices getDevices() {
        return this.devices;
    }
    
    public void setDevices(Devices devices) {
        this.devices = devices;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getSpare() {
        return this.spare;
    }
    
    public void setSpare(String spare) {
        this.spare = spare;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


