package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer id;
     private Domain domain;
     private Person person;
     private Rolls rolls;
     private String username;
     private String password;
     private Integer status;
     private Date regtime;
     private Set logs = new HashSet(0);

    public Login() {
    }

	
    public Login(Domain domain, Person person, Rolls rolls) {
        this.domain = domain;
        this.person = person;
        this.rolls = rolls;
    }
    public Login(Domain domain, Person person, Rolls rolls, String username, String password, Integer status, Date regtime, Set logs) {
       this.domain = domain;
       this.person = person;
       this.rolls = rolls;
       this.username = username;
       this.password = password;
       this.status = status;
       this.regtime = regtime;
       this.logs = logs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Rolls getRolls() {
        return this.rolls;
    }
    
    public void setRolls(Rolls rolls) {
        this.rolls = rolls;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


