package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Logsource generated by hbm2java
 */
public class Logsource  implements java.io.Serializable {


     private Integer id;
     private String ip;
     private String username;
     private String password;
     private String type;
     private Integer status;
     private String comment;
     private Set tracklogs = new HashSet(0);

    public Logsource() {
    }

    public Logsource(String ip, String username, String password, String type, Integer status, String comment, Set tracklogs) {
       this.ip = ip;
       this.username = username;
       this.password = password;
       this.type = type;
       this.status = status;
       this.comment = comment;
       this.tracklogs = tracklogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set getTracklogs() {
        return this.tracklogs;
    }
    
    public void setTracklogs(Set tracklogs) {
        this.tracklogs = tracklogs;
    }




}


