package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1



/**
 * Milage generated by hbm2java
 */
public class Milage  implements java.io.Serializable {


     private Integer id;
     private Devices devices;
     private Double milage;
     private String comment;
     private String status;
     private String speed;

    public Milage() {
    }

	
    public Milage(Devices devices) {
        this.devices = devices;
    }
    public Milage(Devices devices, Double milage, String comment, String status, String speed) {
       this.devices = devices;
       this.milage = milage;
       this.comment = comment;
       this.status = status;
       this.speed = speed;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Devices getDevices() {
        return this.devices;
    }
    
    public void setDevices(Devices devices) {
        this.devices = devices;
    }
    public Double getMilage() {
        return this.milage;
    }
    
    public void setMilage(Double milage) {
        this.milage = milage;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }




}


