package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Objts generated by hbm2java
 */
public class Objts  implements java.io.Serializable {


     private Integer id;
     private Customers customers;
     private Type type;
     private String number;
     private String comment;
     private String description;
     private Date regtime;
     private Set deviceses = new HashSet(0);
     private Set imageses = new HashSet(0);

    public Objts() {
    }

	
    public Objts(Type type) {
        this.type = type;
    }
    public Objts(Customers customers, Type type, String number, String comment, String description, Date regtime, Set deviceses, Set imageses) {
       this.customers = customers;
       this.type = type;
       this.number = number;
       this.comment = comment;
       this.description = description;
       this.regtime = regtime;
       this.deviceses = deviceses;
       this.imageses = imageses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Set getDeviceses() {
        return this.deviceses;
    }
    
    public void setDeviceses(Set deviceses) {
        this.deviceses = deviceses;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


