package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rolls generated by hbm2java
 */
public class Rolls  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer status;
     private Set rollHasActivitieses = new HashSet(0);
     private Set logins = new HashSet(0);

    public Rolls() {
    }

    public Rolls(String name, Integer status, Set rollHasActivitieses, Set logins) {
       this.name = name;
       this.status = status;
       this.rollHasActivitieses = rollHasActivitieses;
       this.logins = logins;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getRollHasActivitieses() {
        return this.rollHasActivitieses;
    }
    
    public void setRollHasActivitieses(Set rollHasActivitieses) {
        this.rollHasActivitieses = rollHasActivitieses;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }




}


