package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarrif generated by hbm2java
 */
public class Tarrif  implements java.io.Serializable {


     private Integer id;
     private Chargetype chargetype;
     private String name;
     private Double charge;
     private Integer status;
     private Set customersHasTarrifs = new HashSet(0);

    public Tarrif() {
    }

	
    public Tarrif(Chargetype chargetype) {
        this.chargetype = chargetype;
    }
    public Tarrif(Chargetype chargetype, String name, Double charge, Integer status, Set customersHasTarrifs) {
       this.chargetype = chargetype;
       this.name = name;
       this.charge = charge;
       this.status = status;
       this.customersHasTarrifs = customersHasTarrifs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Chargetype getChargetype() {
        return this.chargetype;
    }
    
    public void setChargetype(Chargetype chargetype) {
        this.chargetype = chargetype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getCharge() {
        return this.charge;
    }
    
    public void setCharge(Double charge) {
        this.charge = charge;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCustomersHasTarrifs() {
        return this.customersHasTarrifs;
    }
    
    public void setCustomersHasTarrifs(Set customersHasTarrifs) {
        this.customersHasTarrifs = customersHasTarrifs;
    }




}


