package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tracklog generated by hbm2java
 */
public class Tracklog  implements java.io.Serializable {


     private Integer id;
     private Devices devices;
     private Logsource logsource;
     private Date regtime;
     private String lat;
     private String lon;
     private String speed;
     private String acc;
     private String input1;
     private String input2;
     private String input3;
     private String input4;
     private String gps;
     private Integer status;
     private Date time;
     private Date stime;
     private String course;
     private String fual;
     private String milage;

    public Tracklog() {
    }

    public Tracklog(Devices devices, Logsource logsource, Date regtime, String lat, String lon, String speed, String acc, String input1, String input2, String input3, String input4, String gps, Integer status, Date time, Date stime, String course, String fual, String milage) {
       this.devices = devices;
       this.logsource = logsource;
       this.regtime = regtime;
       this.lat = lat;
       this.lon = lon;
       this.speed = speed;
       this.acc = acc;
       this.input1 = input1;
       this.input2 = input2;
       this.input3 = input3;
       this.input4 = input4;
       this.gps = gps;
       this.status = status;
       this.time = time;
       this.stime = stime;
       this.course = course;
       this.fual = fual;
       this.milage = milage;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Devices getDevices() {
        return this.devices;
    }
    
    public void setDevices(Devices devices) {
        this.devices = devices;
    }
    public Logsource getLogsource() {
        return this.logsource;
    }
    
    public void setLogsource(Logsource logsource) {
        this.logsource = logsource;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }
    public String getAcc() {
        return this.acc;
    }
    
    public void setAcc(String acc) {
        this.acc = acc;
    }
    public String getInput1() {
        return this.input1;
    }
    
    public void setInput1(String input1) {
        this.input1 = input1;
    }
    public String getInput2() {
        return this.input2;
    }
    
    public void setInput2(String input2) {
        this.input2 = input2;
    }
    public String getInput3() {
        return this.input3;
    }
    
    public void setInput3(String input3) {
        this.input3 = input3;
    }
    public String getInput4() {
        return this.input4;
    }
    
    public void setInput4(String input4) {
        this.input4 = input4;
    }
    public String getGps() {
        return this.gps;
    }
    
    public void setGps(String gps) {
        this.gps = gps;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Date getStime() {
        return this.stime;
    }
    
    public void setStime(Date stime) {
        this.stime = stime;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public String getFual() {
        return this.fual;
    }
    
    public void setFual(String fual) {
        this.fual = fual;
    }
    public String getMilage() {
        return this.milage;
    }
    
    public void setMilage(String milage) {
        this.milage = milage;
    }




}


