package com.websystique.springmvc.model;
// Generated Apr 4, 2017 3:35:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer status;
     private Set objtses = new HashSet(0);

    public Type() {
    }

    public Type(String name, Integer status, Set objtses) {
       this.name = name;
       this.status = status;
       this.objtses = objtses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getObjtses() {
        return this.objtses;
    }
    
    public void setObjtses(Set objtses) {
        this.objtses = objtses;
    }




}


